// Pure reference data and lookup; preserve literal values and insertion order.
export const OFFICIAL_ECONOVARIA_COUNTRY_CODES = [
  "NORTHREACH",
  "YRETHIA",
  "THALORIS",
  "SOLVEND",
  "ELDORAN",
  "VALERION",
  "LUMENOR",
  "SYNDALIS",
  "XALVORIA",
  "DRAVENLOK",
] as const;

export type OfficialEconovariaCountryCode =
  typeof OFFICIAL_ECONOVARIA_COUNTRY_CODES[number];

export const SUPPORTED_STOCK_MARKET_SECTOR_KEYS = [
  "ENERGY",
  "RARE_MINERALS",
  "SHIPPING_LOGISTICS",
  "TECHNOLOGY",
  "AI_AEROSPACE",
  "AGRICULTURE_COMMODITIES",
  "FOOD_SECURITY",
  "FINANCE_INSURANCE",
  "DEFENSE_SECURITY",
  "CONSUMER_GOODS",
  "CLEAN_ENERGY",
  "INFRASTRUCTURE",
  "REPAIR_SALVAGE_RE_EXPORT_TRADE",
  "EDUCATION_MEDIA_DIPLOMACY",
  "CYBERSECURITY_FINTECH_DATA",
  "HEAVY_INDUSTRY_MANUFACTURING",
  "LUXURY_PREMIUM_SERVICES",
] as const;

export interface EconovariaCountryExposureProfile {
  readonly countryCode: OfficialEconovariaCountryCode;
  readonly countryName: string;
  readonly capitalMarket: string;
  readonly bloc: string;
  readonly focusAreas: readonly string[];
  readonly sectorWeights: Readonly<Record<string, number>>;
  readonly globalDemandSensitivity: number;
  readonly infrastructureSensitivity: number;
  readonly energySensitivity: number;
  readonly riskSensitivity: number;
  readonly politicalStabilitySensitivity: number;
  readonly baseBiasPct: number;
}

export const ECONOVARIA_COUNTRY_EXPOSURE_PROFILES: Readonly<
  Record<OfficialEconovariaCountryCode, EconovariaCountryExposureProfile>
> = {
  NORTHREACH: {
    countryCode: "NORTHREACH",
    countryName: "Northreach",
    capitalMarket: "Frostgate",
    bloc: "Northern Resource Bloc",
    focusAreas: ["rare minerals", "energy", "defense", "arctic logistics"],
    sectorWeights: {
      RARE_MINERALS: 0.34,
      MATERIALS: 0.32,
      ENERGY: 0.28,
      DEFENSE_SECURITY: 0.18,
      DEFENSE: 0.16,
      ARCTIC_LOGISTICS: 0.14,
      SHIPPING_LOGISTICS: 0.14,
      LOGISTICS: 0.14,
      INDUSTRIALS: 0.1,
    },
    globalDemandSensitivity: 0.58,
    infrastructureSensitivity: 0.24,
    energySensitivity: 0.72,
    riskSensitivity: -0.34,
    politicalStabilitySensitivity: 0.2,
    baseBiasPct: 0.03,
  },
  YRETHIA: {
    countryCode: "YRETHIA",
    countryName: "Yrethia",
    capitalMarket: "Sableport",
    bloc: "Western Maritime Corridor",
    focusAreas: ["shipping", "insurance", "freight finance", "regulated trade"],
    sectorWeights: {
      SHIPPING_LOGISTICS: 0.32,
      SHIPPING: 0.3,
      LOGISTICS: 0.24,
      FINANCE_INSURANCE: 0.24,
      FINANCE: 0.22,
      INSURANCE: 0.2,
      FREIGHT_FINANCE: 0.18,
      REGULATED_TRADE: 0.16,
      TRADE: 0.16,
      SERVICES: 0.08,
    },
    globalDemandSensitivity: 0.66,
    infrastructureSensitivity: 0.38,
    energySensitivity: 0.18,
    riskSensitivity: -0.22,
    politicalStabilitySensitivity: 0.26,
    baseBiasPct: 0.02,
  },
  THALORIS: {
    countryCode: "THALORIS",
    countryName: "Thaloris",
    capitalMarket: "Dusk Harbor",
    bloc: "Western Maritime Corridor",
    focusAreas: ["re-export trade", "salvage", "high-risk logistics"],
    sectorWeights: {
      REPAIR_SALVAGE_RE_EXPORT_TRADE: 0.34,
      RE_EXPORT_TRADE: 0.32,
      TRADE: 0.3,
      LOGISTICS: 0.28,
      SALVAGE: 0.22,
      REPAIR: 0.16,
      SHIPPING_LOGISTICS: 0.22,
      SHIPPING: 0.2,
      MATERIALS: 0.12,
      SERVICES: 0.1,
    },
    globalDemandSensitivity: 0.62,
    infrastructureSensitivity: 0.2,
    energySensitivity: 0.2,
    riskSensitivity: -0.48,
    politicalStabilitySensitivity: 0.12,
    baseBiasPct: -0.01,
  },
  SOLVEND: {
    countryCode: "SOLVEND",
    countryName: "Solvend",
    capitalMarket: "Aurora Spire",
    bloc: "Northern Resource Bloc",
    focusAreas: ["AI", "aerospace", "research", "precision engineering"],
    sectorWeights: {
      AI_AEROSPACE: 0.36,
      AI: 0.36,
      TECHNOLOGY: 0.34,
      AEROSPACE: 0.24,
      RESEARCH: 0.18,
      PRECISION_ENGINEERING: 0.16,
      INDUSTRIALS: 0.14,
      EDUCATION: 0.1,
    },
    globalDemandSensitivity: 0.34,
    infrastructureSensitivity: 0.32,
    energySensitivity: 0.16,
    riskSensitivity: -0.18,
    politicalStabilitySensitivity: 0.22,
    baseBiasPct: 0.04,
  },
  ELDORAN: {
    countryCode: "ELDORAN",
    countryName: "Eldoran",
    capitalMarket: "Crescent Bay",
    bloc: "Central Stability Zone",
    focusAreas: ["agriculture", "commodities", "food security", "internal logistics"],
    sectorWeights: {
      AGRICULTURE_COMMODITIES: 0.36,
      AGRICULTURE: 0.34,
      COMMODITIES: 0.22,
      FOOD_SECURITY: 0.2,
      FOOD: 0.18,
      INTERNAL_LOGISTICS: 0.14,
      SHIPPING_LOGISTICS: 0.14,
      LOGISTICS: 0.14,
      CONSUMER_GOODS: 0.12,
      CONSUMER: 0.12,
    },
    globalDemandSensitivity: 0.32,
    infrastructureSensitivity: 0.34,
    energySensitivity: 0.22,
    riskSensitivity: -0.16,
    politicalStabilitySensitivity: 0.28,
    baseBiasPct: 0.02,
  },
  VALERION: {
    countryCode: "VALERION",
    countryName: "Valerion",
    capitalMarket: "Glassfall",
    bloc: "Central Stability Zone",
    focusAreas: ["clean energy", "water infrastructure", "premium services", "finance"],
    sectorWeights: {
      CLEAN_ENERGY: 0.24,
      ENERGY: 0.22,
      WATER_INFRASTRUCTURE: 0.22,
      UTILITIES: 0.2,
      INFRASTRUCTURE: 0.2,
      LUXURY_PREMIUM_SERVICES: 0.18,
      PREMIUM_SERVICES: 0.18,
      SERVICES: 0.18,
      FINANCE_INSURANCE: 0.2,
      FINANCE: 0.2,
    },
    globalDemandSensitivity: 0.28,
    infrastructureSensitivity: 0.5,
    energySensitivity: 0.46,
    riskSensitivity: -0.14,
    politicalStabilitySensitivity: 0.34,
    baseBiasPct: 0.03,
  },
  LUMENOR: {
    countryCode: "LUMENOR",
    countryName: "Lumenor",
    capitalMarket: "Starfall",
    bloc: "Central Stability Zone",
    focusAreas: ["education", "media", "diplomacy", "public services"],
    sectorWeights: {
      EDUCATION_MEDIA_DIPLOMACY: 0.32,
      EDUCATION: 0.28,
      MEDIA: 0.22,
      DIPLOMACY: 0.22,
      PUBLIC_SERVICES: 0.2,
      SERVICES: 0.2,
      CIVIC_LEGITIMACY: 0.16,
      HEALTHCARE: 0.14,
      TECHNOLOGY: 0.16,
    },
    globalDemandSensitivity: 0.2,
    infrastructureSensitivity: 0.24,
    energySensitivity: 0.12,
    riskSensitivity: -0.12,
    politicalStabilitySensitivity: 0.44,
    baseBiasPct: 0.01,
  },
  SYNDALIS: {
    countryCode: "SYNDALIS",
    countryName: "Syndalis",
    capitalMarket: "Blacklight",
    bloc: "Eastern Pressure Zone",
    focusAreas: ["cybersecurity", "fintech", "data centers", "covert market influence"],
    sectorWeights: {
      CYBERSECURITY_FINTECH_DATA: 0.36,
      CYBERSECURITY: 0.32,
      FINTECH: 0.24,
      TECHNOLOGY: 0.22,
      DATA_CENTERS: 0.18,
      DATA: 0.18,
      FINANCE_INSURANCE: 0.12,
      FINANCE: 0.12,
      INFRASTRUCTURE: 0.1,
    },
    globalDemandSensitivity: 0.34,
    infrastructureSensitivity: 0.34,
    energySensitivity: 0.32,
    riskSensitivity: -0.4,
    politicalStabilitySensitivity: 0.12,
    baseBiasPct: 0,
  },
  XALVORIA: {
    countryCode: "XALVORIA",
    countryName: "Xalvoria",
    capitalMarket: "Emberhall",
    bloc: "Eastern Pressure Zone",
    focusAreas: ["banking", "infrastructure finance", "luxury industry", "capital influence"],
    sectorWeights: {
      BANKING: 0.32,
      FINANCE_INSURANCE: 0.3,
      FINANCE: 0.28,
      INFRASTRUCTURE_FINANCE: 0.2,
      INFRASTRUCTURE: 0.18,
      LUXURY_PREMIUM_SERVICES: 0.14,
      LUXURY: 0.12,
      SERVICES: 0.1,
      CAPITAL_INFLUENCE: 0.1,
    },
    globalDemandSensitivity: 0.3,
    infrastructureSensitivity: 0.4,
    energySensitivity: 0.12,
    riskSensitivity: -0.38,
    politicalStabilitySensitivity: 0.16,
    baseBiasPct: 0.01,
  },
  DRAVENLOK: {
    countryCode: "DRAVENLOK",
    countryName: "Dravenlok",
    capitalMarket: "Ironhold",
    bloc: "Eastern Pressure Zone",
    focusAreas: ["steel", "machinery", "defense manufacturing", "heavy logistics"],
    sectorWeights: {
      HEAVY_INDUSTRY_MANUFACTURING: 0.32,
      STEEL: 0.26,
      INDUSTRIALS: 0.24,
      DEFENSE_SECURITY: 0.22,
      DEFENSE_MANUFACTURING: 0.22,
      DEFENSE: 0.2,
      MACHINERY: 0.18,
      SHIPPING_LOGISTICS: 0.12,
      HEAVY_LOGISTICS: 0.12,
      LOGISTICS: 0.12,
    },
    globalDemandSensitivity: 0.48,
    infrastructureSensitivity: 0.34,
    energySensitivity: 0.34,
    riskSensitivity: -0.36,
    politicalStabilitySensitivity: 0.1,
    baseBiasPct: -0.01,
  },
};

export function getCountryExposureProfile(
  countryCode: string,
): EconovariaCountryExposureProfile | undefined {
  return ECONOVARIA_COUNTRY_EXPOSURE_PROFILES[
    normalizeCountryCode(countryCode) as OfficialEconovariaCountryCode
  ];
}

export function normalizeCountryCode(value: string): string {
  return value.trim().toUpperCase();
}
