const MAX_QR_SVG_BYTES = 1_000_000;
const SUPABASE_SVG_DATA_URL = /^data:image\/svg\+xml;utf-8,/iu;

export function normalizeMfaQrCode(value: unknown): string {
  let svg = String(value || "").trim();
  const prefix = SUPABASE_SVG_DATA_URL.exec(svg);
  if (!prefix) return "";
  svg = svg.slice(prefix[0].length).trim();

  const bytes = new TextEncoder().encode(svg);
  if (bytes.byteLength === 0 || bytes.byteLength > MAX_QR_SVG_BYTES) return "";
  if (
    /<!DOCTYPE\b|<!ENTITY\b|<\?xml-stylesheet\b/iu.test(svg) ||
    /<(?:script|foreignObject|iframe|object|embed|style|image|use|a)\b/iu.test(svg) ||
    /\son[a-z]+\s*=/iu.test(svg) ||
    /(?:href|xlink:href)\s*=/iu.test(svg)
  ) {
    return "";
  }

  const root = /^\s*<\?xml version="1\.0"\?>\s*<!-- Generated by SVGo -->\s*<svg width="(\d+)" height="(\d+)"\s+xmlns="http:\/\/www\.w3\.org\/2000\/svg"\s+xmlns:xlink="http:\/\/www\.w3\.org\/1999\/xlink">([\s\S]*)<\/svg>\s*$/u.exec(svg);
  if (!root) return "";

  const width = Number(root[1]);
  const height = Number(root[2]);
  if (
    !Number.isSafeInteger(width) ||
    width !== height ||
    width < 87 ||
    width > 555 ||
    width % 3 !== 0
  ) {
    return "";
  }

  const modules = width / 3 - 8;
  if (
    !Number.isSafeInteger(modules) ||
    modules < 21 ||
    modules > 177 ||
    (modules - 21) % 4 !== 0
  ) {
    return "";
  }

  const body = root[3];
  const rect = /\s*<rect x="(\d+)" y="(\d+)" width="3" height="3" style="fill:(black|white);stroke:none"\s*\/\s*>/gyu;
  const expected = modules * modules;
  const maximumCoordinate = 12 + (modules - 1) * 3;
  const seen = new Set<string>();
  let count = 0;
  let cursor = 0;

  while (cursor < body.length) {
    rect.lastIndex = cursor;
    const match = rect.exec(body);
    if (!match) {
      if (/^\s*$/u.test(body.slice(cursor))) break;
      return "";
    }

    const x = Number(match[1]);
    const y = Number(match[2]);
    if (
      x < 12 ||
      y < 12 ||
      x > maximumCoordinate ||
      y > maximumCoordinate ||
      x % 3 !== 0 ||
      y % 3 !== 0
    ) {
      return "";
    }

    const coordinate = `${x}:${y}`;
    if (seen.has(coordinate)) return "";
    seen.add(coordinate);
    count += 1;
    cursor = rect.lastIndex;
    if (count > expected) return "";
  }

  if (count !== expected) return "";

  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return `data:image/svg+xml;base64,${btoa(binary)}`;
}
