const MAX_QR_SVG_BYTES = 1_000_000;
const MAX_COMPACT_QR_DATA_URL_LENGTH = 1_000_000;
const SUPABASE_SVG_DATA_URL = /^data:image\/svg\+xml;utf-8,/iu;

export function normalizeMfaQrCode(value: unknown): string {
  let svg = String(value || "").trim();
  const prefix = SUPABASE_SVG_DATA_URL.exec(svg);
  if (!prefix) return "";
  svg = svg.slice(prefix[0].length).trim();

  const bytes = new TextEncoder().encode(svg);
  if (bytes.byteLength === 0 || bytes.byteLength > MAX_QR_SVG_BYTES) return "";
  if (
    /<!DOCTYPE\b|<!ENTITY\b|<\?xml-stylesheet\b/iu.test(svg) ||
    /<(?:script|foreignObject|iframe|object|embed|style|image|use|a)\b/iu.test(svg) ||
    /\son[a-z]+\s*=/iu.test(svg) ||
    /(?:href|xlink:href)\s*=/iu.test(svg)
  ) {
    return "";
  }

  const root = /^\s*<\?xml version="1\.0"\?>\s*<!-- Generated by SVGo -->\s*<svg width="(\d+)" height="(\d+)"\s+xmlns="http:\/\/www\.w3\.org\/2000\/svg"\s+xmlns:xlink="http:\/\/www\.w3\.org\/1999\/xlink">([\s\S]*)<\/svg>\s*$/u.exec(svg);
  if (!root) return "";

  const width = Number(root[1]);
  const height = Number(root[2]);
  if (
    !Number.isSafeInteger(width) ||
    width !== height ||
    width < 87 ||
    width > 555 ||
    width % 3 !== 0
  ) {
    return "";
  }

  const modules = width / 3 - 8;
  if (
    !Number.isSafeInteger(modules) ||
    modules < 21 ||
    modules > 177 ||
    (modules - 21) % 4 !== 0
  ) {
    return "";
  }

  const body = root[3];
  const rect = /\s*<rect x="(\d+)" y="(\d+)" width="3" height="3" style="fill:(black|white);stroke:none"\s*\/\s*>/gyu;
  const expected = modules * modules;
  const maximumCoordinate = 12 + (modules - 1) * 3;
  const seen = new Set<string>();
  const blackCells = new Set<string>();
  let count = 0;
  let cursor = 0;

  while (cursor < body.length) {
    rect.lastIndex = cursor;
    const match = rect.exec(body);
    if (!match) {
      if (/^\s*$/u.test(body.slice(cursor))) break;
      return "";
    }

    const x = Number(match[1]);
    const y = Number(match[2]);
    if (
      x < 12 ||
      y < 12 ||
      x > maximumCoordinate ||
      y > maximumCoordinate ||
      x % 3 !== 0 ||
      y % 3 !== 0
    ) {
      return "";
    }

    const column = x / 3 - 4;
    const row = y / 3 - 4;
    const coordinate = `${column}:${row}`;
    if (seen.has(coordinate)) return "";
    seen.add(coordinate);
    if (match[3] === "black") blackCells.add(coordinate);
    count += 1;
    cursor = rect.lastIndex;
    if (count > expected) return "";
  }

  if (count !== expected || blackCells.size === 0 || blackCells.size === expected) return "";

  const compactSvg = buildCompactQrSvg(modules, blackCells);
  const dataUrl = `data:image/svg+xml;base64,${btoa(compactSvg)}`;
  return dataUrl.length <= MAX_COMPACT_QR_DATA_URL_LENGTH ? dataUrl : "";
}

function buildCompactQrSvg(modules: number, blackCells: ReadonlySet<string>): string {
  const size = modules + 8;
  const segments: string[] = [];

  for (let row = 0; row < modules; row += 1) {
    let runStart = -1;
    for (let column = 0; column <= modules; column += 1) {
      const black = column < modules && blackCells.has(`${column}:${row}`);
      if (black && runStart < 0) {
        runStart = column;
        continue;
      }
      if (!black && runStart >= 0) {
        const x = runStart + 4;
        const y = row + 4;
        const length = column - runStart;
        segments.push(`M${x} ${y}h${length}v1h-${length}z`);
        runStart = -1;
      }
    }
  }

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}" width="${size}" height="${size}" shape-rendering="crispEdges"><rect width="${size}" height="${size}" fill="#fff"/><path fill="#000" d="${segments.join("")}"/></svg>`;
}
