export const COUNTRY_ECONOMIC_BASELINE_LIMITS = {
  realGdpIndex: { min: 50, max: 200 },
  gdpGrowthRate: { min: -0.25, max: 0.5 },
  inflationRate: { min: -0.05, max: 0.5 },
  unemploymentRate: { min: 0, max: 0.5 },
  interestRate: { min: 0, max: 0.5 },
  consumerConfidenceIndex: { min: 25, max: 200 },
  businessConfidenceIndex: { min: 25, max: 200 },
  costOfLivingIndex: { min: 0.5, max: 2 },
  regionalPriceMultiplier: { min: 0.5, max: 2 },
  supplyConstraintIndex: { min: 0.5, max: 2 },
  importDependencyIndex: { min: 0.5, max: 2 },
  taxRate: { min: 0, max: 0.5 },
  subsidyRate: { min: 0, max: 0.5 },
  exchangeRateIndex: { min: 0.5, max: 2 },
  currencyStabilityIndex: { min: 0.5, max: 2 },
  tradeBalanceIndex: { min: -100, max: 100 },
  exportStrengthIndex: { min: 0.5, max: 2 },
  marketRiskIndex: { min: 0.5, max: 2 },
  politicalStabilityIndex: { min: 0.5, max: 2 },
  infrastructureIndex: { min: 0.5, max: 2 },
  energySecurityIndex: { min: 0.5, max: 2 },
} as const;

export type CountryEconomicBaselineField = keyof typeof COUNTRY_ECONOMIC_BASELINE_LIMITS;
