import {
  AdminField,
  AdminValidationSummary,
} from "../../components/index.js";
import { createElement, createId } from "../../components/dom.js";
import {
  isAdminErrorEnvelope,
  normalizeAdminError,
} from "../../core/error-envelope.js";

const STORE_CURRENCY_CODES = Object.freeze([
  "NRC",
  "YRC",
  "THD",
  "SLV",
  "ELD",
  "VAL",
  "LUM",
  "SYN",
  "XAL",
  "DRV",
]);

function fieldId(formId, name) {
  return `${formId}-${name}`;
}

function numericValue(value) {
  if (value === "") return null;
  const number = Number(value);
  return Number.isFinite(number) ? number : null;
}

function fieldError(field, message) {
  field.setError(message);
  return {
    fieldId: field.control.id,
    label: field.label.textContent.replace(/Required$/i, "").trim(),
    message,
  };
}

/**
 * Composes the persisted Store item fields shared by Add and Edit dialogs.
 * Item keys are generated by the authoritative create contract; media, item
 * type, stock mode, fulfillment and usage fields are intentionally absent.
 */
export function StoreItemForm({
  mode = "create",
  item = null,
  onSubmit = async () => ({ ok: false }),
  onCancel = () => {},
} = {}) {
  const editing = mode === "edit";
  const formId = createId(`admin-store-${editing ? "edit" : "create"}`);
  const form = createElement("form", {
    className: "admin-store-form",
    attrs: { id: formId, novalidate: true },
  });

  const validation = AdminValidationSummary();
  const name = AdminField({
    id: fieldId(formId, "name"),
    name: "name",
    label: "Item name",
    required: true,
    value: item?.name || "",
    autocomplete: "off",
  });
  const description = AdminField({
    id: fieldId(formId, "description"),
    name: "description",
    label: "Description",
    type: "textarea",
    value: item?.description || "",
    autocomplete: "off",
  });
  const category = AdminField({
    id: fieldId(formId, "category"),
    name: "category",
    label: "Category",
    hint: "Lowercase letters, numbers, underscores, or hyphens.",
    required: true,
    value: item?.category || "general",
    autocomplete: "off",
  });
  const price = AdminField({
    id: fieldId(formId, "price"),
    name: "price",
    label: "Price",
    type: "number",
    required: true,
    value: item?.price ?? 0,
  });
  price.control.min = "0";
  price.control.step = "0.01";

  const currencyCode = AdminField({
    id: fieldId(formId, "currencyCode"),
    name: "currencyCode",
    label: "Currency",
    type: "select",
    required: true,
    value: item?.currencyCode || "",
    options: [
      { value: "", label: "Select currency", disabled: true },
      ...STORE_CURRENCY_CODES.map((code) => ({ value: code, label: code })),
    ],
  });
  const stockQuantity = AdminField({
    id: fieldId(formId, "stockQuantity"),
    name: "stockQuantity",
    label: "Available quantity",
    hint: "The current contract supports finite stock only. Use 0 for out of stock.",
    type: "number",
    required: true,
    value: item?.stockQuantity ?? 0,
  });
  stockQuantity.control.min = "0";
  stockQuantity.control.step = "1";

  const status = AdminField({
    id: fieldId(formId, "status"),
    name: "status",
    label: "Status",
    type: "select",
    required: true,
    value: item?.status || "active",
    options: [
      { value: "active", label: "Active" },
      { value: "disabled", label: "Disabled" },
    ],
  });
  const visibility = AdminField({
    id: fieldId(formId, "visibility"),
    name: "visibility",
    label: "Visibility",
    type: "select",
    required: true,
    value: item?.visibility || "visible",
    options: [
      { value: "visible", label: "Visible" },
      { value: "hidden", label: "Hidden" },
    ],
  });
  const sortOrder = AdminField({
    id: fieldId(formId, "sortOrder"),
    name: "sortOrder",
    label: "Display order",
    type: "number",
    required: true,
    value: item?.sortOrder ?? 0,
  });
  sortOrder.control.step = "1";

  const fields = {
    name,
    description,
    category,
    price,
    currencyCode,
    stockQuantity,
    status,
    visibility,
    sortOrder,
  };
  const fieldGrid = createElement("div", {
    className: "admin-store-form__grid",
    children: [
      name.element,
      category.element,
      price.element,
      currencyCode.element,
      stockQuantity.element,
      status.element,
      visibility.element,
      sortOrder.element,
    ],
  });
  description.element.classList.add("admin-store-form__wide");
  form.append(validation.element, fieldGrid, description.element);

  const cancelButton = createElement("button", {
    className: "admin-button admin-button--quiet",
    attrs: { type: "button", "data-dialog-action": "cancel" },
    text: "Cancel",
  });
  const submitButton = createElement("button", {
    className: "admin-button",
    attrs: {
      type: "submit",
      form: formId,
      "data-dialog-action": "save",
      "data-autofocus": editing ? null : "",
    },
    text: editing ? "Save changes" : "Add item",
  });
  const footer = createElement("div", {
    className: "admin-store-form__actions",
    children: [cancelButton, submitButton],
  });

  let busy = false;

  function clearErrors() {
    Object.values(fields).forEach((field) => field.setError(""));
    validation.setErrors([]);
  }

  function values() {
    return {
      name: name.getValue().trim(),
      description: description.getValue().trim() || null,
      category: category.getValue().trim().toLowerCase(),
      price: numericValue(price.getValue()),
      currencyCode: currencyCode.getValue().trim().toUpperCase(),
      stockQuantity: numericValue(stockQuantity.getValue()),
      status: status.getValue(),
      visibility: visibility.getValue(),
      sortOrder: numericValue(sortOrder.getValue()),
    };
  }

  function validate() {
    clearErrors();
    const input = values();
    const errors = [];
    if (!input.name) errors.push(fieldError(name, "Enter an item name."));
    if (!/^[a-z0-9_-]{1,32}$/.test(input.category)) {
      errors.push(fieldError(category, "Use 1 to 32 lowercase letters, numbers, underscores, or hyphens."));
    }
    if (input.price === null || input.price < 0) {
      errors.push(fieldError(price, "Enter a non-negative price."));
    }
    if (!STORE_CURRENCY_CODES.includes(input.currencyCode)) {
      errors.push(fieldError(currencyCode, "Select an authoritative Store currency."));
    }
    if (!Number.isSafeInteger(input.stockQuantity) || input.stockQuantity < 0) {
      errors.push(fieldError(stockQuantity, "Enter a non-negative whole quantity."));
    }
    if (!Number.isSafeInteger(input.sortOrder)) {
      errors.push(fieldError(sortOrder, "Enter a whole-number display order."));
    }
    validation.setErrors(errors, { focus: errors.length > 0 });
    return errors.length === 0 ? input : null;
  }

  function setBusy(nextBusy) {
    busy = Boolean(nextBusy);
    form.setAttribute("aria-busy", busy ? "true" : "false");
    Object.values(fields).forEach((field) => field.setDisabled(busy));
    cancelButton.disabled = busy;
    submitButton.disabled = busy;
    submitButton.textContent = busy
      ? (editing ? "Saving…" : "Adding…")
      : (editing ? "Save changes" : "Add item");
  }

  function setServerError(error) {
    const envelope = isAdminErrorEnvelope(error)
      ? error
      : normalizeAdminError(error, { fieldErrors: error?.fieldErrors });
    const safeMessage = envelope.userMessage;
    const serverErrors = [];
    const fieldErrors = envelope.fieldErrors;
    Object.entries(fieldErrors).forEach(([fieldName, message]) => {
      const field = fields[fieldName] || (fieldName === "stock" ? stockQuantity : null);
      if (!field) return;
      serverErrors.push(fieldError(field, String(message || "Review this field and try again.")));
    });
    if (serverErrors.length === 0) {
      serverErrors.push({
        fieldId: name.control.id,
        label: "Store item",
        message: safeMessage,
      });
    }
    validation.setErrors(serverErrors, { focus: true });
  }

  cancelButton.addEventListener("click", onCancel);
  form.addEventListener("submit", async (event) => {
    event.preventDefault();
    if (busy) return;
    const input = validate();
    if (!input) return;
    setBusy(true);
    try {
      const result = await onSubmit(input);
      if (result?.ok !== true) setServerError(result?.error);
    } catch (_error) {
      setServerError(null);
    } finally {
      setBusy(false);
    }
  });

  return {
    element: form,
    footer,
    fields: Object.freeze(fields),
    cancelButton,
    submitButton,
    validate,
    values,
    setBusy,
    setServerError,
    focus() { name.focus(); },
  };
}

export const ADMIN_STORE_CURRENCY_CODES = STORE_CURRENCY_CODES;
