-- Read-only catalog metadata. Function bodies and scheduler commands are hashed.
-- No application rows, credentials, URLs or scheduler command literals are exported.
begin transaction read only;
select jsonb_build_object(
 'schemaVersion','econovaria.phase15.catalog-supplement.v1',
 'schemas',(select coalesce(jsonb_agg(jsonb_build_object('name',nspname,'owner',pg_get_userbyid(nspowner)) order by nspname),'[]'::jsonb) from pg_namespace where nspname not like 'pg_%' and nspname <> 'information_schema'),
 'extensions',(select coalesce(jsonb_agg(jsonb_build_object('name',e.extname,'version',e.extversion,'schema',n.nspname) order by e.extname),'[]'::jsonb) from pg_extension e join pg_namespace n on n.oid=e.extnamespace),
 'views',(select coalesce(jsonb_agg(jsonb_build_object('schema',n.nspname,'name',c.relname,'owner',pg_get_userbyid(c.relowner),'options',c.reloptions,'definitionSha256',encode(sha256(convert_to(pg_get_viewdef(c.oid,false),'UTF8')),'hex')) order by n.nspname,c.relname),'[]'::jsonb) from pg_class c join pg_namespace n on n.oid=c.relnamespace where c.relkind in ('v','m') and n.nspname not like 'pg_%' and n.nspname <> 'information_schema'),
 'routineSecurity',(select coalesce(jsonb_agg(jsonb_build_object('schema',n.nspname,'name',p.proname,'arguments',pg_get_function_identity_arguments(p.oid),'owner',pg_get_userbyid(p.proowner),'securityDefiner',p.prosecdef,'searchPath',(select split_part(x,'=',2) from unnest(p.proconfig) x where x like 'search_path=%'),'configurationSha256',encode(sha256(convert_to(coalesce(to_jsonb(p.proconfig)::text,'null'),'UTF8')),'hex'),'definitionSha256',encode(sha256(convert_to(pg_get_functiondef(p.oid),'UTF8')),'hex')) order by n.nspname,p.proname,pg_get_function_identity_arguments(p.oid)),'[]'::jsonb) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where p.prokind in ('f','p') and n.nspname not like 'pg_%' and n.nspname <> 'information_schema' and not exists(select 1 from pg_depend d where d.classid='pg_proc'::regclass and d.objid=p.oid and d.deptype='e')),
 'triggers',(select coalesce(jsonb_agg(jsonb_build_object('schema',n.nspname,'table',c.relname,'name',t.tgname,'enabled',t.tgenabled,'definitionSha256',encode(sha256(convert_to(pg_get_triggerdef(t.oid,false),'UTF8')),'hex')) order by n.nspname,c.relname,t.tgname),'[]'::jsonb) from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where not t.tgisinternal and n.nspname not like 'pg_%' and n.nspname <> 'information_schema'),
 'cron',(select coalesce(jsonb_agg(jsonb_build_object('name',jobname,'schedule',schedule,'active',active,'database',database,'username',username,'commandSha256',encode(sha256(convert_to(command,'UTF8')),'hex')) order by jobname,schedule,command),'[]'::jsonb) from cron.job)
) as snapshot;
rollback;
