import assert from "node:assert/strict";
import test from "node:test";

import { normalizeMfaQrCode } from "../backend/supabase/functions/staff-mfa-api/mfaQrCode.ts";

function supabaseSvg(modules = 21) {
  const width = (modules + 8) * 3;
  const rectangles = [];
  for (let row = 0; row < modules; row += 1) {
    for (let column = 0; column < modules; column += 1) {
      const x = 12 + column * 3;
      const y = 12 + row * 3;
      const fill = (row + column) % 2 === 0 ? "black" : "white";
      rectangles.push(
        `<rect x="${x}" y="${y}" width="3" height="3" style="fill:${fill};stroke:none" />`,
      );
    }
  }
  return `<?xml version="1.0"?>\n<!-- Generated by SVGo -->\n<svg width="${width}" height="${width}"\n     xmlns="http://www.w3.org/2000/svg"\n     xmlns:xlink="http://www.w3.org/1999/xlink">\n${rectangles.join("\n")}\n</svg>\n`;
}

function sdkPayload(svg) {
  return `data:image/svg+xml;utf-8,${svg}`;
}

function decodeSvg(dataUrl) {
  const prefix = "data:image/svg+xml;base64,";
  assert.ok(dataUrl.startsWith(prefix));
  return Buffer.from(dataUrl.slice(prefix.length), "base64").toString("utf8");
}

function assertCompactStaticQr(dataUrl, modules) {
  const compact = decodeSvg(dataUrl);
  const size = modules + 8;
  assert.match(
    compact,
    new RegExp(`^<svg xmlns="http://www\\.w3\\.org/2000/svg" viewBox="0 0 ${size} ${size}" width="${size}" height="${size}" shape-rendering="crispEdges">`),
  );
  assert.match(compact, /<rect width="\d+" height="\d+" fill="#fff"\/>/u);
  assert.match(compact, /<path fill="#000" d="M/u);
  assert.doesNotMatch(compact, /<\?xml|<!--|xmlns:xlink|<script|<image|href=/iu);
  return compact;
}

test("reconstructs the exact Supabase SDK TOTP QR payload as a compact inert SVG", () => {
  const normalized = normalizeMfaQrCode(sdkPayload(supabaseSvg()));
  const compact = assertCompactStaticQr(normalized, 21);
  assert.ok(compact.length < 20_000);
});

test("compacts large static Supabase QR output below the browser transport bound", () => {
  const svg = supabaseSvg(81);
  assert.ok(Buffer.byteLength(svg, "utf8") > 200_000);
  const normalized = normalizeMfaQrCode(sdkPayload(svg));
  assertCompactStaticQr(normalized, 81);
  assert.ok(normalized.length < 200_000);
});

test("rejects non-Supabase serialization forms", () => {
  const svg = supabaseSvg();
  assert.equal(normalizeMfaQrCode(svg), "");
  assert.equal(normalizeMfaQrCode(`data:image/svg+xml;utf8,${svg}`), "");
  assert.equal(normalizeMfaQrCode(`data:image/svg+xml;utf-8,${encodeURIComponent(svg)}`), "");
  assert.equal(normalizeMfaQrCode("data:image/png;base64,iVBORw0KGgo="), "");
});

test("rejects executable, externally referenced, or structurally altered SVG", () => {
  const svg = supabaseSvg();
  assert.equal(normalizeMfaQrCode(sdkPayload(svg.replace("</svg>", "<script/></svg>"))), "");
  assert.equal(normalizeMfaQrCode(sdkPayload(svg.replace("</svg>", '<image href="https://example.com/x"/></svg>'))), "");
  assert.equal(normalizeMfaQrCode(sdkPayload(svg.replace("<!-- Generated by SVGo -->", "<!DOCTYPE svg>"))), "");
  assert.equal(normalizeMfaQrCode(sdkPayload(svg.replace(/<rect[^>]+\/>\n/u, ""))), "");
  assert.equal(normalizeMfaQrCode(sdkPayload(svg.replace('width="3" height="3"', 'width="4" height="3"'))), "");
});
